In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as mtp

print(torch.__version__)

2.9.0+cpu


scalar
vector
matrix
tensor

In [ ]:
scalar = torch.tensor(2)
print(scalar.ndim)
print(scalar.item())

0
2


In [ ]:
vector = torch.tensor([2, 2])
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([
    [2, 2],
    [2, 2]
])
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [4, 8, 12],
        [16, 32, 48]
    ]
])
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2304, 0.7041, 0.4761, 0.1813],
        [0.0246, 0.4743, 0.5110, 0.6634],
        [0.8997, 0.1172, 0.0213, 0.1779]])

In [ ]:
random_image_size_tensor = torch.rand(size=(1440, 1440, 3)) # height, weight, color channels (R, G, B)
random_image_size_tensor[0][0]

tensor([0.5419, 0.1190, 0.8537])

In [ ]:
matrix_with_zeros = torch.zeros(3, 4)
matrix_with_zeros
matrix_with_zeros.dtype # by default float32

torch.float32

In [ ]:
matrix_with_ones = torch.ones(3, 4)
matrix_with_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
range_tensor = torch.arange(start=0, end=1001, step=100)
range_tensor

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
zeros_like = torch.zeros_like(input=range_tensor) # or ones_like
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# **Manipulation**

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor * 10
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)